import Head from "next/head";
import Link from "next/link";

const getCounters = async () => {
  const res = await fetch('http://127.0.0.1:8090/api/collections/counters/records?page=1&perPage=30', {cache: 'no-store'});
  const data = await res.json();
  return data.items as any[];
}   

const CounterThumbnail = ({counter}: any) => { // props always in {} for tsx too
  return(
    <Link href={`/counters/${counter.id}`}>
      <div>{counter.title}</div>
    </Link>
  )
}


export default async function page() {
  const counters = await getCounters()
  return(   
    <>    
      <Head>
        <title>Collective Push Up Counter | All counters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <div>
          <h1>
            All counters:
          </h1>
          {counters.map((counter: any) => {
            return <CounterThumbnail counter={counter} />;
          })}
        </div>
      </body>
    </>
  )
}
