'use client'

import Head from 'next/head'
import * as React from 'react'


export default function Home() {
  const [sessionToken, setSessionToken] = React.useState("")
  return (
    <>
      <Head>
        <title>Collective Push Up Counter | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <h1> Collective Pushup Counter </h1>
        { 
          (sessionToken === "") ?
            <div className='signInBox'>
              Sign In:
              
            </div>
          :
            <div></div>
        }
        <div>
          
          <div className='signUpBox'>
            Create an account (Free):

          </div>
        </div>
        <div>
          With an account, you can:
          <li>Join various collective counters</li>
          <li>Add to a collective counter</li>
          <li>View the leaderboards on a collective counter</li>
          <li>View the a calender of contributions to a collective counter</li>
          <li>See a projected finish time according to the current counter completion rate</li>
        </div>
      </body>
    </>
  )
}
